// <auto-generated />
using CoordinatesApi.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoordinatesApi.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CoordinatesApi.Data.Entities.Rectangle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("X1")
                        .HasColumnType("int");

                    b.Property<int>("X2")
                        .HasColumnType("int");

                    b.Property<int>("Y1")
                        .HasColumnType("int");

                    b.Property<int>("Y2")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("X1", "Y1", "X2", "Y2");

                    b.ToTable("Rectangles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            X1 = 49,
                            X2 = 79,
                            Y1 = 40,
                            Y2 = 72
                        },
                        new
                        {
                            Id = 2,
                            X1 = 59,
                            X2 = 69,
                            Y1 = 27,
                            Y2 = 57
                        },
                        new
                        {
                            Id = 3,
                            X1 = 49,
                            X2 = 82,
                            Y1 = 92,
                            Y2 = 97
                        },
                        new
                        {
                            Id = 4,
                            X1 = 19,
                            X2 = 60,
                            Y1 = 21,
                            Y2 = 41
                        },
                        new
                        {
                            Id = 5,
                            X1 = 73,
                            X2 = 102,
                            Y1 = 0,
                            Y2 = 18
                        },
                        new
                        {
                            Id = 6,
                            X1 = 24,
                            X2 = 65,
                            Y1 = 26,
                            Y2 = 40
                        },
                        new
                        {
                            Id = 7,
                            X1 = 38,
                            X2 = 40,
                            Y1 = 96,
                            Y2 = 126
                        },
                        new
                        {
                            Id = 8,
                            X1 = 2,
                            X2 = 42,
                            Y1 = 79,
                            Y2 = 111
                        },
                        new
                        {
                            Id = 9,
                            X1 = 94,
                            X2 = 112,
                            Y1 = 50,
                            Y2 = 96
                        },
                        new
                        {
                            Id = 10,
                            X1 = 73,
                            X2 = 90,
                            Y1 = 26,
                            Y2 = 39
                        },
                        new
                        {
                            Id = 11,
                            X1 = 50,
                            X2 = 89,
                            Y1 = 18,
                            Y2 = 47
                        },
                        new
                        {
                            Id = 12,
                            X1 = 9,
                            X2 = 42,
                            Y1 = 3,
                            Y2 = 30
                        },
                        new
                        {
                            Id = 13,
                            X1 = 88,
                            X2 = 115,
                            Y1 = 60,
                            Y2 = 70
                        },
                        new
                        {
                            Id = 14,
                            X1 = 2,
                            X2 = 6,
                            Y1 = 82,
                            Y2 = 124
                        },
                        new
                        {
                            Id = 15,
                            X1 = 98,
                            X2 = 114,
                            Y1 = 53,
                            Y2 = 69
                        },
                        new
                        {
                            Id = 16,
                            X1 = 81,
                            X2 = 118,
                            Y1 = 15,
                            Y2 = 52
                        },
                        new
                        {
                            Id = 17,
                            X1 = 76,
                            X2 = 110,
                            Y1 = 12,
                            Y2 = 41
                        },
                        new
                        {
                            Id = 18,
                            X1 = 93,
                            X2 = 128,
                            Y1 = 23,
                            Y2 = 64
                        },
                        new
                        {
                            Id = 19,
                            X1 = 47,
                            X2 = 47,
                            Y1 = 75,
                            Y2 = 120
                        },
                        new
                        {
                            Id = 20,
                            X1 = 75,
                            X2 = 106,
                            Y1 = 84,
                            Y2 = 124
                        },
                        new
                        {
                            Id = 21,
                            X1 = 68,
                            X2 = 69,
                            Y1 = 21,
                            Y2 = 31
                        },
                        new
                        {
                            Id = 22,
                            X1 = 25,
                            X2 = 49,
                            Y1 = 16,
                            Y2 = 57
                        },
                        new
                        {
                            Id = 23,
                            X1 = 15,
                            X2 = 18,
                            Y1 = 13,
                            Y2 = 27
                        },
                        new
                        {
                            Id = 24,
                            X1 = 1,
                            X2 = 36,
                            Y1 = 18,
                            Y2 = 44
                        },
                        new
                        {
                            Id = 25,
                            X1 = 15,
                            X2 = 52,
                            Y1 = 4,
                            Y2 = 15
                        },
                        new
                        {
                            Id = 26,
                            X1 = 48,
                            X2 = 95,
                            Y1 = 62,
                            Y2 = 102
                        },
                        new
                        {
                            Id = 27,
                            X1 = 46,
                            X2 = 93,
                            Y1 = 1,
                            Y2 = 14
                        },
                        new
                        {
                            Id = 28,
                            X1 = 14,
                            X2 = 37,
                            Y1 = 84,
                            Y2 = 100
                        },
                        new
                        {
                            Id = 29,
                            X1 = 76,
                            X2 = 120,
                            Y1 = 62,
                            Y2 = 81
                        },
                        new
                        {
                            Id = 30,
                            X1 = 69,
                            X2 = 117,
                            Y1 = 21,
                            Y2 = 58
                        },
                        new
                        {
                            Id = 31,
                            X1 = 91,
                            X2 = 92,
                            Y1 = 6,
                            Y2 = 42
                        },
                        new
                        {
                            Id = 32,
                            X1 = 88,
                            X2 = 93,
                            Y1 = 23,
                            Y2 = 63
                        },
                        new
                        {
                            Id = 33,
                            X1 = 30,
                            X2 = 55,
                            Y1 = 4,
                            Y2 = 13
                        },
                        new
                        {
                            Id = 34,
                            X1 = 62,
                            X2 = 93,
                            Y1 = 31,
                            Y2 = 43
                        },
                        new
                        {
                            Id = 35,
                            X1 = 45,
                            X2 = 70,
                            Y1 = 81,
                            Y2 = 114
                        },
                        new
                        {
                            Id = 36,
                            X1 = 2,
                            X2 = 18,
                            Y1 = 53,
                            Y2 = 69
                        },
                        new
                        {
                            Id = 37,
                            X1 = 84,
                            X2 = 116,
                            Y1 = 10,
                            Y2 = 57
                        },
                        new
                        {
                            Id = 38,
                            X1 = 80,
                            X2 = 91,
                            Y1 = 52,
                            Y2 = 65
                        },
                        new
                        {
                            Id = 39,
                            X1 = 57,
                            X2 = 73,
                            Y1 = 96,
                            Y2 = 105
                        },
                        new
                        {
                            Id = 40,
                            X1 = 87,
                            X2 = 129,
                            Y1 = 39,
                            Y2 = 77
                        },
                        new
                        {
                            Id = 41,
                            X1 = 71,
                            X2 = 83,
                            Y1 = 16,
                            Y2 = 19
                        },
                        new
                        {
                            Id = 42,
                            X1 = 67,
                            X2 = 77,
                            Y1 = 26,
                            Y2 = 30
                        },
                        new
                        {
                            Id = 43,
                            X1 = 85,
                            X2 = 86,
                            Y1 = 66,
                            Y2 = 96
                        },
                        new
                        {
                            Id = 44,
                            X1 = 54,
                            X2 = 79,
                            Y1 = 52,
                            Y2 = 84
                        },
                        new
                        {
                            Id = 45,
                            X1 = 57,
                            X2 = 94,
                            Y1 = 13,
                            Y2 = 20
                        },
                        new
                        {
                            Id = 46,
                            X1 = 83,
                            X2 = 112,
                            Y1 = 67,
                            Y2 = 103
                        },
                        new
                        {
                            Id = 47,
                            X1 = 25,
                            X2 = 47,
                            Y1 = 79,
                            Y2 = 113
                        },
                        new
                        {
                            Id = 48,
                            X1 = 58,
                            X2 = 85,
                            Y1 = 91,
                            Y2 = 102
                        },
                        new
                        {
                            Id = 49,
                            X1 = 59,
                            X2 = 68,
                            Y1 = 81,
                            Y2 = 126
                        },
                        new
                        {
                            Id = 50,
                            X1 = 64,
                            X2 = 104,
                            Y1 = 75,
                            Y2 = 119
                        },
                        new
                        {
                            Id = 51,
                            X1 = 47,
                            X2 = 85,
                            Y1 = 45,
                            Y2 = 59
                        },
                        new
                        {
                            Id = 52,
                            X1 = 79,
                            X2 = 96,
                            Y1 = 18,
                            Y2 = 57
                        },
                        new
                        {
                            Id = 53,
                            X1 = 9,
                            X2 = 40,
                            Y1 = 2,
                            Y2 = 2
                        },
                        new
                        {
                            Id = 54,
                            X1 = 99,
                            X2 = 147,
                            Y1 = 37,
                            Y2 = 61
                        },
                        new
                        {
                            Id = 55,
                            X1 = 61,
                            X2 = 110,
                            Y1 = 10,
                            Y2 = 56
                        },
                        new
                        {
                            Id = 56,
                            X1 = 86,
                            X2 = 107,
                            Y1 = 70,
                            Y2 = 92
                        },
                        new
                        {
                            Id = 57,
                            X1 = 87,
                            X2 = 93,
                            Y1 = 91,
                            Y2 = 133
                        },
                        new
                        {
                            Id = 58,
                            X1 = 90,
                            X2 = 124,
                            Y1 = 28,
                            Y2 = 44
                        },
                        new
                        {
                            Id = 59,
                            X1 = 10,
                            X2 = 12,
                            Y1 = 62,
                            Y2 = 111
                        },
                        new
                        {
                            Id = 60,
                            X1 = 64,
                            X2 = 76,
                            Y1 = 61,
                            Y2 = 93
                        },
                        new
                        {
                            Id = 61,
                            X1 = 23,
                            X2 = 48,
                            Y1 = 36,
                            Y2 = 53
                        },
                        new
                        {
                            Id = 62,
                            X1 = 96,
                            X2 = 130,
                            Y1 = 33,
                            Y2 = 59
                        },
                        new
                        {
                            Id = 63,
                            X1 = 55,
                            X2 = 73,
                            Y1 = 81,
                            Y2 = 110
                        },
                        new
                        {
                            Id = 64,
                            X1 = 78,
                            X2 = 112,
                            Y1 = 13,
                            Y2 = 40
                        },
                        new
                        {
                            Id = 65,
                            X1 = 66,
                            X2 = 86,
                            Y1 = 45,
                            Y2 = 47
                        },
                        new
                        {
                            Id = 66,
                            X1 = 40,
                            X2 = 68,
                            Y1 = 58,
                            Y2 = 93
                        },
                        new
                        {
                            Id = 67,
                            X1 = 4,
                            X2 = 18,
                            Y1 = 39,
                            Y2 = 73
                        },
                        new
                        {
                            Id = 68,
                            X1 = 40,
                            X2 = 82,
                            Y1 = 36,
                            Y2 = 70
                        },
                        new
                        {
                            Id = 69,
                            X1 = 89,
                            X2 = 89,
                            Y1 = 56,
                            Y2 = 99
                        },
                        new
                        {
                            Id = 70,
                            X1 = 7,
                            X2 = 54,
                            Y1 = 89,
                            Y2 = 105
                        },
                        new
                        {
                            Id = 71,
                            X1 = 75,
                            X2 = 95,
                            Y1 = 77,
                            Y2 = 109
                        },
                        new
                        {
                            Id = 72,
                            X1 = 49,
                            X2 = 96,
                            Y1 = 52,
                            Y2 = 76
                        },
                        new
                        {
                            Id = 73,
                            X1 = 29,
                            X2 = 32,
                            Y1 = 8,
                            Y2 = 57
                        },
                        new
                        {
                            Id = 74,
                            X1 = 57,
                            X2 = 60,
                            Y1 = 6,
                            Y2 = 33
                        },
                        new
                        {
                            Id = 75,
                            X1 = 32,
                            X2 = 52,
                            Y1 = 87,
                            Y2 = 128
                        },
                        new
                        {
                            Id = 76,
                            X1 = 28,
                            X2 = 37,
                            Y1 = 4,
                            Y2 = 20
                        },
                        new
                        {
                            Id = 77,
                            X1 = 94,
                            X2 = 108,
                            Y1 = 20,
                            Y2 = 27
                        },
                        new
                        {
                            Id = 78,
                            X1 = 16,
                            X2 = 48,
                            Y1 = 41,
                            Y2 = 50
                        },
                        new
                        {
                            Id = 79,
                            X1 = 97,
                            X2 = 119,
                            Y1 = 97,
                            Y2 = 112
                        },
                        new
                        {
                            Id = 80,
                            X1 = 23,
                            X2 = 66,
                            Y1 = 30,
                            Y2 = 74
                        },
                        new
                        {
                            Id = 81,
                            X1 = 43,
                            X2 = 81,
                            Y1 = 9,
                            Y2 = 13
                        },
                        new
                        {
                            Id = 82,
                            X1 = 10,
                            X2 = 32,
                            Y1 = 21,
                            Y2 = 51
                        },
                        new
                        {
                            Id = 83,
                            X1 = 41,
                            X2 = 54,
                            Y1 = 51,
                            Y2 = 90
                        },
                        new
                        {
                            Id = 84,
                            X1 = 78,
                            X2 = 114,
                            Y1 = 34,
                            Y2 = 79
                        },
                        new
                        {
                            Id = 85,
                            X1 = 36,
                            X2 = 56,
                            Y1 = 5,
                            Y2 = 16
                        },
                        new
                        {
                            Id = 86,
                            X1 = 89,
                            X2 = 106,
                            Y1 = 19,
                            Y2 = 31
                        },
                        new
                        {
                            Id = 87,
                            X1 = 0,
                            X2 = 12,
                            Y1 = 82,
                            Y2 = 130
                        },
                        new
                        {
                            Id = 88,
                            X1 = 53,
                            X2 = 91,
                            Y1 = 36,
                            Y2 = 85
                        },
                        new
                        {
                            Id = 89,
                            X1 = 3,
                            X2 = 9,
                            Y1 = 24,
                            Y2 = 34
                        },
                        new
                        {
                            Id = 90,
                            X1 = 18,
                            X2 = 21,
                            Y1 = 11,
                            Y2 = 18
                        },
                        new
                        {
                            Id = 91,
                            X1 = 69,
                            X2 = 72,
                            Y1 = 49,
                            Y2 = 51
                        },
                        new
                        {
                            Id = 92,
                            X1 = 8,
                            X2 = 38,
                            Y1 = 48,
                            Y2 = 56
                        },
                        new
                        {
                            Id = 93,
                            X1 = 10,
                            X2 = 58,
                            Y1 = 51,
                            Y2 = 55
                        },
                        new
                        {
                            Id = 94,
                            X1 = 1,
                            X2 = 12,
                            Y1 = 65,
                            Y2 = 68
                        },
                        new
                        {
                            Id = 95,
                            X1 = 19,
                            X2 = 30,
                            Y1 = 83,
                            Y2 = 110
                        },
                        new
                        {
                            Id = 96,
                            X1 = 94,
                            X2 = 116,
                            Y1 = 77,
                            Y2 = 126
                        },
                        new
                        {
                            Id = 97,
                            X1 = 26,
                            X2 = 50,
                            Y1 = 34,
                            Y2 = 74
                        },
                        new
                        {
                            Id = 98,
                            X1 = 22,
                            X2 = 59,
                            Y1 = 10,
                            Y2 = 52
                        },
                        new
                        {
                            Id = 99,
                            X1 = 76,
                            X2 = 108,
                            Y1 = 4,
                            Y2 = 19
                        },
                        new
                        {
                            Id = 100,
                            X1 = 7,
                            X2 = 56,
                            Y1 = 22,
                            Y2 = 30
                        },
                        new
                        {
                            Id = 101,
                            X1 = 16,
                            X2 = 40,
                            Y1 = 36,
                            Y2 = 59
                        },
                        new
                        {
                            Id = 102,
                            X1 = 56,
                            X2 = 89,
                            Y1 = 85,
                            Y2 = 95
                        },
                        new
                        {
                            Id = 103,
                            X1 = 84,
                            X2 = 111,
                            Y1 = 44,
                            Y2 = 70
                        },
                        new
                        {
                            Id = 104,
                            X1 = 58,
                            X2 = 85,
                            Y1 = 53,
                            Y2 = 98
                        },
                        new
                        {
                            Id = 105,
                            X1 = 22,
                            X2 = 43,
                            Y1 = 33,
                            Y2 = 69
                        },
                        new
                        {
                            Id = 106,
                            X1 = 82,
                            X2 = 94,
                            Y1 = 82,
                            Y2 = 103
                        },
                        new
                        {
                            Id = 107,
                            X1 = 14,
                            X2 = 25,
                            Y1 = 31,
                            Y2 = 47
                        },
                        new
                        {
                            Id = 108,
                            X1 = 34,
                            X2 = 42,
                            Y1 = 80,
                            Y2 = 100
                        },
                        new
                        {
                            Id = 109,
                            X1 = 79,
                            X2 = 88,
                            Y1 = 54,
                            Y2 = 85
                        },
                        new
                        {
                            Id = 110,
                            X1 = 39,
                            X2 = 64,
                            Y1 = 10,
                            Y2 = 59
                        },
                        new
                        {
                            Id = 111,
                            X1 = 10,
                            X2 = 38,
                            Y1 = 62,
                            Y2 = 91
                        },
                        new
                        {
                            Id = 112,
                            X1 = 83,
                            X2 = 91,
                            Y1 = 28,
                            Y2 = 48
                        },
                        new
                        {
                            Id = 113,
                            X1 = 8,
                            X2 = 37,
                            Y1 = 78,
                            Y2 = 99
                        },
                        new
                        {
                            Id = 114,
                            X1 = 66,
                            X2 = 72,
                            Y1 = 98,
                            Y2 = 133
                        },
                        new
                        {
                            Id = 115,
                            X1 = 86,
                            X2 = 101,
                            Y1 = 36,
                            Y2 = 51
                        },
                        new
                        {
                            Id = 116,
                            X1 = 71,
                            X2 = 76,
                            Y1 = 25,
                            Y2 = 29
                        },
                        new
                        {
                            Id = 117,
                            X1 = 47,
                            X2 = 52,
                            Y1 = 94,
                            Y2 = 126
                        },
                        new
                        {
                            Id = 118,
                            X1 = 89,
                            X2 = 101,
                            Y1 = 44,
                            Y2 = 59
                        },
                        new
                        {
                            Id = 119,
                            X1 = 45,
                            X2 = 94,
                            Y1 = 88,
                            Y2 = 134
                        },
                        new
                        {
                            Id = 120,
                            X1 = 38,
                            X2 = 40,
                            Y1 = 46,
                            Y2 = 78
                        },
                        new
                        {
                            Id = 121,
                            X1 = 97,
                            X2 = 141,
                            Y1 = 38,
                            Y2 = 76
                        },
                        new
                        {
                            Id = 122,
                            X1 = 84,
                            X2 = 116,
                            Y1 = 71,
                            Y2 = 96
                        },
                        new
                        {
                            Id = 123,
                            X1 = 79,
                            X2 = 93,
                            Y1 = 3,
                            Y2 = 36
                        },
                        new
                        {
                            Id = 124,
                            X1 = 23,
                            X2 = 31,
                            Y1 = 37,
                            Y2 = 64
                        },
                        new
                        {
                            Id = 125,
                            X1 = 26,
                            X2 = 40,
                            Y1 = 69,
                            Y2 = 99
                        },
                        new
                        {
                            Id = 126,
                            X1 = 31,
                            X2 = 64,
                            Y1 = 42,
                            Y2 = 54
                        },
                        new
                        {
                            Id = 127,
                            X1 = 77,
                            X2 = 122,
                            Y1 = 66,
                            Y2 = 115
                        },
                        new
                        {
                            Id = 128,
                            X1 = 82,
                            X2 = 101,
                            Y1 = 41,
                            Y2 = 55
                        },
                        new
                        {
                            Id = 129,
                            X1 = 90,
                            X2 = 104,
                            Y1 = 39,
                            Y2 = 41
                        },
                        new
                        {
                            Id = 130,
                            X1 = 14,
                            X2 = 39,
                            Y1 = 69,
                            Y2 = 113
                        },
                        new
                        {
                            Id = 131,
                            X1 = 81,
                            X2 = 83,
                            Y1 = 80,
                            Y2 = 100
                        },
                        new
                        {
                            Id = 132,
                            X1 = 14,
                            X2 = 16,
                            Y1 = 44,
                            Y2 = 53
                        },
                        new
                        {
                            Id = 133,
                            X1 = 58,
                            X2 = 58,
                            Y1 = 45,
                            Y2 = 79
                        },
                        new
                        {
                            Id = 134,
                            X1 = 86,
                            X2 = 103,
                            Y1 = 44,
                            Y2 = 71
                        },
                        new
                        {
                            Id = 135,
                            X1 = 6,
                            X2 = 28,
                            Y1 = 86,
                            Y2 = 97
                        },
                        new
                        {
                            Id = 136,
                            X1 = 80,
                            X2 = 121,
                            Y1 = 10,
                            Y2 = 55
                        },
                        new
                        {
                            Id = 137,
                            X1 = 93,
                            X2 = 113,
                            Y1 = 77,
                            Y2 = 104
                        },
                        new
                        {
                            Id = 138,
                            X1 = 33,
                            X2 = 72,
                            Y1 = 15,
                            Y2 = 58
                        },
                        new
                        {
                            Id = 139,
                            X1 = 3,
                            X2 = 20,
                            Y1 = 55,
                            Y2 = 101
                        },
                        new
                        {
                            Id = 140,
                            X1 = 71,
                            X2 = 89,
                            Y1 = 45,
                            Y2 = 91
                        },
                        new
                        {
                            Id = 141,
                            X1 = 29,
                            X2 = 51,
                            Y1 = 1,
                            Y2 = 18
                        },
                        new
                        {
                            Id = 142,
                            X1 = 16,
                            X2 = 41,
                            Y1 = 73,
                            Y2 = 101
                        },
                        new
                        {
                            Id = 143,
                            X1 = 92,
                            X2 = 99,
                            Y1 = 3,
                            Y2 = 18
                        },
                        new
                        {
                            Id = 144,
                            X1 = 72,
                            X2 = 83,
                            Y1 = 20,
                            Y2 = 43
                        },
                        new
                        {
                            Id = 145,
                            X1 = 13,
                            X2 = 42,
                            Y1 = 33,
                            Y2 = 50
                        },
                        new
                        {
                            Id = 146,
                            X1 = 85,
                            X2 = 115,
                            Y1 = 84,
                            Y2 = 84
                        },
                        new
                        {
                            Id = 147,
                            X1 = 27,
                            X2 = 43,
                            Y1 = 16,
                            Y2 = 26
                        },
                        new
                        {
                            Id = 148,
                            X1 = 21,
                            X2 = 36,
                            Y1 = 79,
                            Y2 = 111
                        },
                        new
                        {
                            Id = 149,
                            X1 = 6,
                            X2 = 23,
                            Y1 = 69,
                            Y2 = 113
                        },
                        new
                        {
                            Id = 150,
                            X1 = 39,
                            X2 = 48,
                            Y1 = 93,
                            Y2 = 130
                        },
                        new
                        {
                            Id = 151,
                            X1 = 26,
                            X2 = 32,
                            Y1 = 19,
                            Y2 = 28
                        },
                        new
                        {
                            Id = 152,
                            X1 = 74,
                            X2 = 102,
                            Y1 = 90,
                            Y2 = 139
                        },
                        new
                        {
                            Id = 153,
                            X1 = 45,
                            X2 = 67,
                            Y1 = 49,
                            Y2 = 50
                        },
                        new
                        {
                            Id = 154,
                            X1 = 0,
                            X2 = 15,
                            Y1 = 9,
                            Y2 = 25
                        },
                        new
                        {
                            Id = 155,
                            X1 = 17,
                            X2 = 65,
                            Y1 = 81,
                            Y2 = 112
                        },
                        new
                        {
                            Id = 156,
                            X1 = 44,
                            X2 = 81,
                            Y1 = 0,
                            Y2 = 32
                        },
                        new
                        {
                            Id = 157,
                            X1 = 7,
                            X2 = 14,
                            Y1 = 48,
                            Y2 = 59
                        },
                        new
                        {
                            Id = 158,
                            X1 = 86,
                            X2 = 110,
                            Y1 = 18,
                            Y2 = 22
                        },
                        new
                        {
                            Id = 159,
                            X1 = 93,
                            X2 = 118,
                            Y1 = 38,
                            Y2 = 53
                        },
                        new
                        {
                            Id = 160,
                            X1 = 84,
                            X2 = 89,
                            Y1 = 44,
                            Y2 = 62
                        },
                        new
                        {
                            Id = 161,
                            X1 = 96,
                            X2 = 114,
                            Y1 = 91,
                            Y2 = 109
                        },
                        new
                        {
                            Id = 162,
                            X1 = 97,
                            X2 = 107,
                            Y1 = 20,
                            Y2 = 51
                        },
                        new
                        {
                            Id = 163,
                            X1 = 32,
                            X2 = 60,
                            Y1 = 23,
                            Y2 = 33
                        },
                        new
                        {
                            Id = 164,
                            X1 = 73,
                            X2 = 116,
                            Y1 = 41,
                            Y2 = 70
                        },
                        new
                        {
                            Id = 165,
                            X1 = 6,
                            X2 = 32,
                            Y1 = 72,
                            Y2 = 98
                        },
                        new
                        {
                            Id = 166,
                            X1 = 85,
                            X2 = 97,
                            Y1 = 67,
                            Y2 = 101
                        },
                        new
                        {
                            Id = 167,
                            X1 = 57,
                            X2 = 79,
                            Y1 = 74,
                            Y2 = 99
                        },
                        new
                        {
                            Id = 168,
                            X1 = 44,
                            X2 = 69,
                            Y1 = 5,
                            Y2 = 37
                        },
                        new
                        {
                            Id = 169,
                            X1 = 38,
                            X2 = 80,
                            Y1 = 22,
                            Y2 = 61
                        },
                        new
                        {
                            Id = 170,
                            X1 = 65,
                            X2 = 67,
                            Y1 = 92,
                            Y2 = 105
                        },
                        new
                        {
                            Id = 171,
                            X1 = 4,
                            X2 = 6,
                            Y1 = 54,
                            Y2 = 56
                        },
                        new
                        {
                            Id = 172,
                            X1 = 72,
                            X2 = 75,
                            Y1 = 68,
                            Y2 = 68
                        },
                        new
                        {
                            Id = 173,
                            X1 = 94,
                            X2 = 130,
                            Y1 = 1,
                            Y2 = 35
                        },
                        new
                        {
                            Id = 174,
                            X1 = 83,
                            X2 = 85,
                            Y1 = 36,
                            Y2 = 76
                        },
                        new
                        {
                            Id = 175,
                            X1 = 74,
                            X2 = 103,
                            Y1 = 99,
                            Y2 = 101
                        },
                        new
                        {
                            Id = 176,
                            X1 = 68,
                            X2 = 86,
                            Y1 = 15,
                            Y2 = 43
                        },
                        new
                        {
                            Id = 177,
                            X1 = 99,
                            X2 = 122,
                            Y1 = 54,
                            Y2 = 72
                        },
                        new
                        {
                            Id = 178,
                            X1 = 39,
                            X2 = 86,
                            Y1 = 86,
                            Y2 = 87
                        },
                        new
                        {
                            Id = 179,
                            X1 = 22,
                            X2 = 48,
                            Y1 = 69,
                            Y2 = 90
                        },
                        new
                        {
                            Id = 180,
                            X1 = 27,
                            X2 = 69,
                            Y1 = 36,
                            Y2 = 66
                        },
                        new
                        {
                            Id = 181,
                            X1 = 56,
                            X2 = 59,
                            Y1 = 28,
                            Y2 = 29
                        },
                        new
                        {
                            Id = 182,
                            X1 = 40,
                            X2 = 77,
                            Y1 = 72,
                            Y2 = 118
                        },
                        new
                        {
                            Id = 183,
                            X1 = 86,
                            X2 = 125,
                            Y1 = 73,
                            Y2 = 89
                        },
                        new
                        {
                            Id = 184,
                            X1 = 60,
                            X2 = 74,
                            Y1 = 23,
                            Y2 = 72
                        },
                        new
                        {
                            Id = 185,
                            X1 = 91,
                            X2 = 91,
                            Y1 = 0,
                            Y2 = 33
                        },
                        new
                        {
                            Id = 186,
                            X1 = 38,
                            X2 = 80,
                            Y1 = 42,
                            Y2 = 81
                        },
                        new
                        {
                            Id = 187,
                            X1 = 35,
                            X2 = 71,
                            Y1 = 57,
                            Y2 = 59
                        },
                        new
                        {
                            Id = 188,
                            X1 = 83,
                            X2 = 110,
                            Y1 = 28,
                            Y2 = 28
                        },
                        new
                        {
                            Id = 189,
                            X1 = 21,
                            X2 = 29,
                            Y1 = 14,
                            Y2 = 53
                        },
                        new
                        {
                            Id = 190,
                            X1 = 49,
                            X2 = 49,
                            Y1 = 96,
                            Y2 = 113
                        },
                        new
                        {
                            Id = 191,
                            X1 = 88,
                            X2 = 95,
                            Y1 = 42,
                            Y2 = 60
                        },
                        new
                        {
                            Id = 192,
                            X1 = 63,
                            X2 = 67,
                            Y1 = 40,
                            Y2 = 74
                        },
                        new
                        {
                            Id = 193,
                            X1 = 54,
                            X2 = 86,
                            Y1 = 42,
                            Y2 = 60
                        },
                        new
                        {
                            Id = 194,
                            X1 = 52,
                            X2 = 69,
                            Y1 = 94,
                            Y2 = 137
                        },
                        new
                        {
                            Id = 195,
                            X1 = 80,
                            X2 = 96,
                            Y1 = 69,
                            Y2 = 87
                        },
                        new
                        {
                            Id = 196,
                            X1 = 12,
                            X2 = 35,
                            Y1 = 65,
                            Y2 = 108
                        },
                        new
                        {
                            Id = 197,
                            X1 = 49,
                            X2 = 66,
                            Y1 = 21,
                            Y2 = 38
                        },
                        new
                        {
                            Id = 198,
                            X1 = 55,
                            X2 = 88,
                            Y1 = 22,
                            Y2 = 35
                        },
                        new
                        {
                            Id = 199,
                            X1 = 89,
                            X2 = 119,
                            Y1 = 34,
                            Y2 = 65
                        },
                        new
                        {
                            Id = 200,
                            X1 = 16,
                            X2 = 32,
                            Y1 = 22,
                            Y2 = 56
                        });
                });

            modelBuilder.Entity("CoordinatesApi.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
